name: Deploy to Kubernetes

on:
  workflow_run:
    workflows: ["Build and Publish Docker Image"]  # Specify the name of the previous action workflow
    types:
      - completed
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s-deploy/deployment.yml